steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bolt-diy:$COMMIT_SHA', '--target', 'bolt-ai-production', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bolt-diy:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bolt-diy'
      - '--image=gcr.io/$PROJECT_ID/bolt-diy:$COMMIT_SHA'
      - '--region=us-central1'  # Update with your preferred region
      - '--platform=managed'
      - '--allow-unauthenticated'  # Remove if you don't want public access
      - '--memory=512Mi'  # Adjust as needed
      - '--set-env-vars=RUNNING_IN_DOCKER=true'
      
# Store images in Google Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/bolt-diy:$COMMIT_SHA'